### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by aadrian** [kostapc/Putty-Tunnel-Manager#29]
Hi,

any chance publishing a new release?

Thank you.

**Comment by kostapc** [comment]
Hi! Glad to see you here!

What feature are you waiting for?

**Comment by aadrian** [comment]
> What feature are you waiting for?

#26 , #27 but would be also nice to have current .NET versions as dependency for easier deployments.

**Comment by kostapc** [comment]
Ok, i'll try to do release next days.
Also, what version of .NET is required?
I preffer to use 4.6, as it installed by default in windows 10.

**Comment by aadrian** [comment]
> Ok, i'll try to do release next days.

That sounds great. 

> Also, what version of .NET is required?
> I preffer to use 4.6, as it installed by default in windows 10.

Different tools, require different major versions  (so for 4.6.x that would be 4.6.2)

**Comment by kostapc** [comment]
You are welcome =)
https://github.com/kostapc/Putty-Tunnel-Manager/releases/tag/0.10.0

**Comment by aadrian** [comment]
> Version 0.10.0

@kostapc this is fantastic! 

Thank you very much for the new release and for the great software - it simplifies indeed greatly the handling of ssh tunnels :D .
